# -*- coding: utf-8 -*-
"""DC_Resource_Nexus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXlTY6pF8JeRKzg0wBKWu8p3iZHeh6Qp
"""

# 1. ติดตั้งไลบรารีที่จำเป็น
!pip install geemap

import ee
import geemap
import pandas as pd

# 2. ยืนยันตัวตนกับ Google Earth Engine
ee.Authenticate()
ee.Initialize(project='mami-project-498904')

# 3. ชุดข้อมูล 10 พิกัด Hyperscale Data Centers ที่ครอบคลุมทุกสภาพภูมิอากาศ
dc_locations = {
    # กลุ่มที่ 1: ทะเลทรายและพื้นที่แห้งแล้ง (ประเด็น: แย่งน้ำชุมชนแบบวิกฤต, อมความร้อน)
    'Meta_Mesa_AZ': {'lat': 33.324, 'lon': -111.602, 'climate': 'Desert'},            # แอริโซนา (ร้อนจัด แห้งแล้ง)
    'Apple_Reno_NV': {'lat': 39.556, 'lon': -119.467, 'climate': 'Arid Desert'},      # เนวาดา (เขตทะเลทรายอุตสาหกรรม)
    'Meta_EagleMountain_UT': {'lat': 40.260, 'lon': -112.046, 'climate': 'Cold Desert'}, # ยูทาห์ (ทะเลทรายหนาว ที่สูง)

    # กลุ่มที่ 2: พื้นที่เกษตรกรรมและที่ราบลุ่ม (ประเด็น: ทับซ้อนพื้นที่ทำกิน, การใช้น้ำบาดาล)
    'Google_CouncilBluffs_IA': {'lat': 41.221, 'lon': -95.862, 'climate': 'Midwest/Agri'}, # ไอโอวา (ใจกลางเขตเกษตรกรรมอเมริกา)
    'Meta_NewAlbany_OH': {'lat': 40.091, 'lon': -82.766, 'climate': 'Continental'},        # โอไฮโอ (ใกล้แหล่งน้ำและชุมชนเมือง)

    # กลุ่มที่ 3: เขตป่าไม้และใกล้แหล่งน้ำอุดมสมบูรณ์ (ประเด็น: นิเวศวิทยารอบแม่น้ำ, การปล่อยน้ำร้อนลงแหล่งน้ำ)
    'Google_TheDalles_OR': {'lat': 45.604, 'lon': -121.144, 'climate': 'River/Cool'},      # ออริกอน (ริมแม่น้ำโคลัมเบีย)
    'Meta_Prineville_OR': {'lat': 44.301, 'lon': -120.814, 'climate': 'High Desert'},      # ออริกอน (พื้นที่กึ่งแห้งแล้งในรัฐที่น้ำเยอะ)
    'Google_Lenoir_NC': {'lat': 35.897, 'lon': -81.547, 'climate': 'Subtropical/Forest'},  # นอร์ทแคโรไลนา (เขตป่าชื้น)

    # กลุ่มที่ 4: เขตร้อนชื้นและเมืองหนาแน่น (ประเด็น: การใช้ไฟสูง, ความร้อนสะสมในเขตเมือง - Urban Heat Island)
    'AWS_Ashburn_VA': {'lat': 39.018, 'lon': -77.472, 'climate': 'Dense Urban'},           # เวอร์จิเนีย (หนาแน่นที่สุดในโลก)
    'Microsoft_SanAntonio_TX': {'lat': 29.435, 'lon': -98.694, 'climate': 'South/Heat'}    # เท็กซัส (ร้อนชื้น แย่งโครงข่ายไฟฟ้า)
}

# 4. ฟังก์ชันสำหรับสร้าง Buffer รัศมี 5 กิโลเมตรรอบพิกัด (ใช้เป็นพื้นที่ไข่แดงในการดึงข้อมูลดาวเทียม)
def create_buffer(lat, lon, radius_meters=5000):
    point = ee.Geometry.Point([lon, lat])
    return point.buffer(radius_meters)

# 5. ทดสอบลูปตรวจสอบและสร้างพื้นที่ (ROI - Region of Interest) ให้ครบทั้ง 10 จุด
roi_dict = {}
for name, coords in dc_locations.items():
    roi = create_buffer(coords['lat'], coords['lon'])
    roi_dict[name] = roi
    print(f"สร้างพื้นที่ตรวจสอบสำหรับ {name} ({coords['climate']}) สำเร็จ")

print(f"\nโหลดพิกัดครบถ้วนทั้ง {len(roi_dict)} จุด พร้อมสำหรับการดึงข้อมูลภาพถ่ายดาวเทียมสำหรับการวิเคราะห์ในขั้นตอนต่อไป")

"""**แผนที่ 10 พิกัด**
แสดงถึงจุดที่เลือกทั้งหมด 10 พิกัดครอบคลุมทุกรูปแบบพื้นที่ในประเทศอเมริกา และเน้นย้ำถึงจุด 4 จุด ที่ผู้วิจัยเลือกนำมาวิเคราะห์ต่อไป
"""

from ipyleaflet import CircleMarker

# 1. กำหนดพิกัด 10 Data Centers (พร้อมจัดกลุ่มและสีให้ตรงกับกราฟ)
dc_locations = {
    'Meta_Mesa_AZ': {'lat': 33.324, 'lon': -111.602, 'role': 'hero', 'color': '#e74c3c'},
    'Google_CouncilBluffs_IA': {'lat': 41.221, 'lon': -95.862, 'role': 'hero', 'color': '#2ecc71'},
    'Google_TheDalles_OR': {'lat': 45.604, 'lon': -121.144, 'role': 'hero', 'color': '#3498db'},
    'AWS_Ashburn_VA': {'lat': 39.018, 'lon': -77.472, 'role': 'hero', 'color': '#f39c12'},

    'Apple_Reno_NV': {'lat': 39.556, 'lon': -119.467, 'role': 'bg', 'color': '#bdc3c7'},
    'Meta_EagleMountain_UT': {'lat': 40.260, 'lon': -112.046, 'role': 'bg', 'color': '#bdc3c7'},
    'Meta_NewAlbany_OH': {'lat': 40.091, 'lon': -82.766, 'role': 'bg', 'color': '#bdc3c7'},
    'Meta_Prineville_OR': {'lat': 44.301, 'lon': -120.814, 'role': 'bg', 'color': '#bdc3c7'},
    'Google_Lenoir_NC': {'lat': 35.897, 'lon': -81.547, 'role': 'bg', 'color': '#bdc3c7'},
    'Microsoft_SanAntonio_TX': {'lat': 29.435, 'lon': -98.694, 'role': 'bg', 'color': '#bdc3c7'}
}

# 2. สร้างแผนที่
Map_Intro = geemap.Map(center=[39.8283, -98.5795], zoom=4)
Map_Intro.add_basemap('CartoDB.DarkMatter')

# 3. วนลูปปักหมุดลงบนแผนที่โดยใช้ ipyleaflet
for key, info in dc_locations.items():
    lat, lon = info['lat'], info['lon']

    #  4 ประเทศที่เลือกใช้งาน ให้หมุดวงกลมใหญ่และมีสีสัน
    if info['role'] == 'hero':
        marker = CircleMarker(
            location=[lat, lon],
            radius=12,
            color=info['color'],
            fill_color=info['color'],
            fill_opacity=0.8,
            weight=2
        )
    # 6 ประเทศที่เหลือ ให้หมุดวงกลมเล็กสีเทาจางๆ
    else:
        marker = CircleMarker(
            location=[lat, lon],
            radius=5,
            color=info['color'],
            fill_color=info['color'],
            fill_opacity=0.4,
            weight=1
        )

    Map_Intro.add_layer(marker)

print("สร้างแผนที่ภาพรวม 10 สถานที่สำเร็จ")
Map_Intro

"""**กลุ่มที่ 1: ทะเลทรายและพื้นที่แห้งแล้ง (ประเด็น: แย่งน้ำชุมชนแบบวิกฤต, อมความร้อน)**

**ตรวจจับความร้อนและการปล่อยตัวความร้อนแฝงรอบๆ**
"""

# 1. กำหนดพิกัดและพื้นที่ (Mesa, Arizona)
lat, lon = 33.324, -111.602
roi = ee.Geometry.Point([lon, lat]).buffer(5000)

# 2. กำหนดช่วงปีที่ต้องการ (2020 ถึง 2025)
years = [2020, 2021, 2022, 2023, 2024, 2025]

# 3. สร้างฟังก์ชันดึงข้อมูลความร้อนของแต่ละปี
def get_lst_image(year):
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # ดึงภาพหน้าร้อนของปีนั้นๆ
    l8 = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2") \
            .filterBounds(roi) \
            .filterDate(start, end) \
            .median() \
            .clip(roi)

    # แปลงเป็นเซลเซียส
    lst = l8.select('ST_B10').multiply(0.00341802).add(149.0).subtract(273.15)

    #ใส่เวลาให้แต่ละภาพ
    return lst.set('system:time_start', ee.Date(start).millis())

# 4. วนลูปสร้างคลังภาพ (ImageCollection) รวมทั้ง 6 ปี
lst_images = [get_lst_image(y) for y in years]
lst_col = ee.ImageCollection.fromImages(lst_images)

# 5. ตั้งค่าสี (35 ถึง 55 องศาเซลเซียส)
lst_vis = {'min': 35, 'max': 55, 'palette': ['yellow', 'orange', 'red', 'darkred']}

# 6. สร้างแผนที่
Map = geemap.Map(center=[lat, lon], zoom=13)

# ใส่เส้นขอบวงกลม
roi_outline = ee.Image().byte().paint(featureCollection=ee.FeatureCollection(roi), color=1, width=2)
Map.addLayer(roi_outline, {'palette': ['black']}, '5km Radius')

# 7. สร้างแถบเลื่อน Time Slider พร้อมแสดงผลเลขปี
labels = [str(y) for y in years]
Map.add_time_slider(lst_col, lst_vis, labels=labels, time_interval=1.5)

# แสดงผล
Map

"""**ตรวจจับความร้อน เปรียบเทียบ ปริมาณน้ำฝน**
วิเคราะห์ว่าความร้อนที่ลดลงหรือเพิ่มขึ้นนั้นเกิดจากปริมาณน้ำฝนใแต่ละช่วงปีหรือไม่
"""

import ee
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. กำหนดพิกัด  Case: Mesa, Arizona
lat, lon = 33.324, -111.602
roi = ee.Geometry.Point([lon, lat]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]

results = []
print("วิเคราะห์ความสัมพันธ์ระหว่าง 'ความร้อน' และ 'ปริมาณน้ำฝน'...")

# 2. วนลูปดึงข้อมูลทั้ง 2 ปัจจัย
#กำหนดหน้าร้อน
for year in years:
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # 2.1 ดึงอุณหภูมิ (LST) จาก Landsat 8
    l8 = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2").filterBounds(roi).filterDate(start, end).median()
    lst = l8.select('ST_B10').multiply(0.00341802).add(149.0).subtract(273.15)
    mean_temp = lst.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi, scale=30, maxPixels=1e9).get('ST_B10').getInfo()

    # 2.2 ดึงปริมาณน้ำฝนรวม (Precipitation) จาก CHIRPS (
    chirps = ee.ImageCollection("UCSB-CHG/CHIRPS/DAILY").filterBounds(roi).filterDate(start, end).sum()
    mean_precip = chirps.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi, scale=5000, maxPixels=1e9).get('precipitation').getInfo()

    # เก็บข้อมูล
    results.append({
        'Year': str(year),
        'Temperature (°C)': round(mean_temp, 2) if mean_temp else 0,
        'Rainfall (mm)': round(mean_precip, 2) if mean_precip else 0
    })

# 3. สร้าง DataFrame
df = pd.DataFrame(results)

# 4. สร้างกราฟแบบแกนคู่ (Dual-Axis Chart)
fig, ax1 = plt.subplots(figsize=(10, 6))

# กราฟแท่ง: ปริมาณน้ำฝน (อยู่แกนซ้าย)
color1 = '#4A90E2'
bars = ax1.bar(df['Year'], df['Rainfall (mm)'], color=color1, alpha=0.6, label='Summer Rainfall (mm)')
ax1.set_xlabel('Year', fontsize=12)
ax1.set_ylabel('Total Rainfall (mm)', color=color1, fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor=color1)

# กราฟเส้น: อุณหภูมิ (อยู่แกนขวา)
ax2 = ax1.twinx()
color2 = '#D0021B'
line = ax2.plot(df['Year'], df['Temperature (°C)'], color=color2, marker='o', linewidth=3, markersize=8, label='Land Surface Temp (°C)')
ax2.set_ylabel('Temperature (°C)', color=color2, fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor=color2)

# จัดการ Title และ Legend
plt.title('Anomaly Detection: Artificial Heat vs Natural Rainfall (Mesa, AZ)', fontsize=14, fontweight='bold')
fig.legend(loc='upper left', bbox_to_anchor=(0.15, 0.85))

# ตกแต่ง
ax1.grid(True, axis='y', linestyle='--', alpha=0.3)
plt.tight_layout()

# แสดงผล
plt.show()

# แสดงตารางให้ดูตัวเลขเป๊ะๆ ด้วย
print("\nตารางเปรียบเทียบข้อมูล:")
print(df.to_string(index=False))

"""**ตรวจสอบระดับความร้อนว่ามีการเพิ่มขึ้นหรือลดลงตามช่วงเวลาของวันหรือเกิดจากปัจจัยอื่นๆ**"""

import ee
import pandas as pd
import matplotlib.pyplot as plt

# 1. กำหนดพิกัดพื้นที่Mesa, Arizona และรัศมี 5 กม.
lat, lon = 33.324, -111.602
roi = ee.Geometry.Point([lon, lat]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]

results = []
print("กำลังสกัดข้อมูลอุณหภูมิกลางวันและกลางคืนปี 2020-2025")

# 2. วนลูปดึงข้อมูลรายปี
for year in years:
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # ดึงภาพดาวเทียม MODIS ช่วงหน้าร้อน
    modis = ee.ImageCollection("MODIS/061/MOD11A1") \
              .filterBounds(roi) \
              .filterDate(start, end) \
              .median()

    # สกัดแบนด์กลางวัน/กลางคืน และแปลงเป็นองศาเซลเซียส (ตัวคูณสเกลของ MODIS คือ 0.02)
    lst_day = modis.select('LST_Day_1km').multiply(0.02).subtract(273.15)
    lst_night = modis.select('LST_Night_1km').multiply(0.02).subtract(273.15)

    # หาค่าเฉลี่ยอุณหภูมิเชิงพื้นที่ในรัศมี 5 กม.
    mean_day = lst_day.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi, scale=1000).get('LST_Day_1km').getInfo()
    mean_night = lst_night.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi, scale=1000).get('LST_Night_1km').getInfo()

    # บันทึกผลลัพธ์
    results.append({
        'Year': year,
        'Daytime Temp (°C)': round(mean_day, 2) if mean_day else None,
        'Nighttime Temp (°C)': round(mean_night, 2) if mean_night else None
    })
    print(f"ประมวลผลปี {year} สำเร็จ")

# 3. แปลงเป็นตาราง DataFrame
df = pd.DataFrame(results)

# 4. พล็อตกราฟเส้นคู่เปรียบเทียบเทรนด์ทุกปี (Day vs Night)
plt.figure(figsize=(11, 6))
plt.plot(df['Year'], df['Daytime Temp (°C)'], marker='o', color='#e74c3c', linewidth=2.5, label='Daytime Heat (แดดธรรมชาติ)')
plt.plot(df['Year'], df['Nighttime Temp (°C)'], marker='s', color='#2c3e50', linewidth=2.5, label='Nighttime Trapped Heat (ความร้อนสะสม)')

# ตกแต่งกราฟ
plt.title('Multi-Year Day vs Night Temperature Trend (2020-2025) - Mesa, AZ', fontsize=13, fontweight='bold')
plt.xlabel('Year', fontsize=11)
plt.ylabel('Temperature (°C)', fontsize=11)
plt.xticks(years)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(loc='upper left')
plt.tight_layout()

# แสดงผลกราฟ
plt.show()

# 5. แสดงตารางตัวเลขดิบสำหรับเอาไปแปะในหน้าสไลด์พรีเซนต์
print("\nชุดข้อมูลสรุปสำหรับนำไปจัดวางบน Dashboard:")
print(df.to_string(index=False))

"""**การหดตัวของแหล่งน้ำ**"""

import ee
import pandas as pd
import matplotlib.pyplot as plt

# 1. กำหนดพิกัดพื้นที่ Mesa, Arizona และรัศมี 5 กม.
lat, lon = 33.324, -111.602
roi = ee.Geometry.Point([lon, lat]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]

water_results = []
print("กำลังใช้ดาวเทียม Sentinel-2 คำนวณพื้นที่การหดตัวของแหล่งน้ำปี 2020-2025")

# 2. วนลูปดึงข้อมูลรายปี
for year in years:
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # ดึงภาพ Sentinel-2 คัดกรองภาพที่เมฆน้อยกว่า 15%
    s2 = ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED") \
           .filterBounds(roi) \
           .filterDate(start, end) \
           .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 15)) \
           .median()

    # คำนวณ NDWI
    ndwi = s2.normalizedDifference(['B3', 'B8'])

    # ตั้งเกณฑ์ (Threshold) พิกเซลที่เป็นน้ำ (ค่า NDWI > 0.0)
    water_mask = ndwi.gt(0.0)

    # คำนวณพื้นที่ผิวน้ำรวม และ "ล็อกชื่อแบนด์" เป็น 'water_area' เพื่อป้องกัน GEE เปลี่ยนชื่อ
    water_area_img = water_mask.multiply(ee.Image.pixelArea()).rename('water_area')

    # รวมพื้นที่พิกเซลทั้งหมดในเขต ROI โดยเรียกใช้ชื่อคีย์ที่ตั้งไว้
    total_water_pixels = water_area_img.reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=roi,
        scale=10,
        maxPixels=1e9
    ).get('water_area')

    area_meters = total_water_pixels.getInfo()

    # แปลงหน่วยจากตารางเมตร เป็น เฮกตาร์ (Hectares)
    area_hectares = round(area_meters / 10000, 2) if area_meters else 0

    water_results.append({
        'Year': year,
        'Water Area (Hectares)': area_hectares
    })
    print(f"คำนวณพื้นที่น้ำปี {year} สำเร็จ")

# 3. แปลงข้อมูลเป็น DataFrame
df_water = pd.DataFrame(water_results)

# 4. พล็อตกราฟเส้นแสดงแนวโน้มการหดตัวของแหล่งน้ำ
plt.figure(figsize=(10, 5))
plt.plot(df_water['Year'], df_water['Water Area (Hectares)'], marker='s', color='#1bc4d9', linewidth=2.5, label='Surface Water Area')

plt.title('Multi-Year Surface Water Shrinkage Trend (2020-2025) - Mesa, AZ', fontsize=13, fontweight='bold')
plt.xlabel('Year', fontsize=11)
plt.ylabel('Water Area (Hectares)', fontsize=11)
plt.xticks(years)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(loc='upper right')
plt.tight_layout()

# แสดงผลกราฟ
plt.show()

# 5. แสดงตารางข้อมูลดิบ
print("\n ตารางสรุปพื้นที่ผิวน้ำรวมรายปี:")
print(df_water.to_string(index=False))

"""**การทรุดตัวของดิน**"""

import ee
import pandas as pd
import matplotlib.pyplot as plt

# 1. กำหนดพิกัดพื้นที่ Mesa, Arizona และรัศมี 5 กม.
lat, lon = 33.324, -111.602
roi = ee.Geometry.Point([lon, lat]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]

sar_results = []
print("กำลังใช้ดาวเทียมเรดาร์ Sentinel-1 สแกนโครงสร้างพื้นผิวเพื่อประเมินความเสี่ยงการทรุดตัว")

# 2. วนลูปดึงข้อมูลเรดาร์รายปี
for year in years:
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # ดึงภาพเรดาร์ Sentinel-1 (C-band Synthetic Aperture Radar)
    s1 = ee.ImageCollection('COPERNICUS/S1_GRD') \
           .filterBounds(roi) \
           .filterDate(start, end) \
           .filter(ee.Filter.eq('instrumentMode', 'IW')) \
           .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV')) \
           .median()

    # ใช้แบนด์ VV (Vertical-Vertical) ซึ่งสะท้อนโครงสร้างคอนกรีตได้ดีที่สุด
    vv_band = s1.select('VV')

    # หาค่าเฉลี่ยการสะท้อนกลับในพื้นที่ (หน่วยเป็น Decibels: dB)
    mean_vv = vv_band.reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=roi,
        scale=10,
        maxPixels=1e9
    ).get('VV').getInfo()

    sar_results.append({
        'Year': year,
        'SAR Backscatter (dB)': round(mean_vv, 2) if mean_vv else None
    })
    print(f"สแกนโครงสร้างเรดาร์ปี {year} สำเร็จ")

# 3. แปลงข้อมูลเป็น DataFrame
df_sar = pd.DataFrame(sar_results)

# 4. พล็อตกราฟเส้นแสดงเทรนด์
plt.figure(figsize=(10, 5))
plt.plot(df_sar['Year'], df_sar['SAR Backscatter (dB)'], marker='D', color='#8e44ad', linewidth=2.5, label='Infrastructure Load (VV dB)')

plt.title('Infrastructure Density & Subsidence Risk Trend (2020-2025) - Mesa, AZ', fontsize=13, fontweight='bold')
plt.xlabel('Year', fontsize=11)
plt.ylabel('SAR Backscatter (dB)', fontsize=11)
plt.xticks(years)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(loc='upper left')
plt.tight_layout()

# แสดงผลกราฟ
plt.show()

# 5. แสดงตารางข้อมูลดิบ
print("\nตารางสรุปค่าความหนาแน่นโครงสร้าง (dB):")
print(df_sar.to_string(index=False))

import ee
import pandas as pd
import matplotlib.pyplot as plt

# 1. พิกัด Mesa, AZ และช่วงเวลา
lat, lon = 33.324, -111.602
roi = ee.Geometry.Point([lon, lat]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]

smap_results = []
print("กำลังดึงข้อมูลความชื้นในดินจาก ERA5-Land (ECMWF) เพื่อนำมาหักล้างข้ออ้างภัยแล้ง")

# 2. ดึงข้อมูล Soil Moisture ของแต่ละปี
for year in years:
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # เปลี่ยนมาใช้ ERA5-Land ซึ่งอัปเดตข้อมูลถึงปัจจุบัน
    era5 = ee.ImageCollection('ECMWF/ERA5_LAND/MONTHLY_AGGR') \
             .filterBounds(roi) \
             .filterDate(start, end) \
             .median()

    # ดึงค่า volumetric_soil_water_layer_1 (ความชื้นในดินชั้นบน 0-7 cm)
    mean_moisture_dict = era5.reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=roi,
        scale=11132, # Resolution ของ ERA5 ประมาณ 11km
        maxPixels=1e9
    ).getInfo()

    # ถ้าดึงค่าได้ให้ใช้ค่านั้น ถ้าไม่ได้ให้เป็น None เพื่อไม่ให้โปรแกรมแคลช
    mean_moisture = mean_moisture_dict.get('volumetric_soil_water_layer_1') if mean_moisture_dict else None

    # ดึงค่า SAR เดิมจาก df_sar
    sar_row = df_sar[df_sar['Year'] == year]
    sar_value = sar_row['SAR Backscatter (dB)'].values[0] if not sar_row.empty else None

    smap_results.append({
        'Year': year,
        'Soil Moisture (m3/m3)': round(mean_moisture, 3) if mean_moisture else 0, # หน่วยเป็นปริมาตรน้ำต่อดิน
        'SAR Backscatter (dB)': sar_value
    })
    print(f"ดึงข้อมูลความชื้นดินปี {year} สำเร็จ")

df_lie_detector = pd.DataFrame(smap_results)

# 3. พล็อตกราฟแกนคู่ (Dual-Axis)
fig, ax1 = plt.subplots(figsize=(11, 6))

# แกนซ้าย: ความชื้นในดิน (ปัจจัยธรรมชาติ)
color1 = '#27ae60'
ax1.bar(df_lie_detector['Year'], df_lie_detector['Soil Moisture (m3/m3)'], color=color1, alpha=0.5, label='Natural Soil Moisture (ERA5)')
ax1.set_xlabel('Year', fontsize=12)
ax1.set_ylabel('Soil Moisture ($m^3/m^3$)', color=color1, fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor=color1)

# แกนขวา: การทรุดตัว/โหลดโครงสร้าง (ปัจจัยมนุษย์)
ax2 = ax1.twinx()
color2 = '#8e44ad'
ax2.plot(df_lie_detector['Year'], df_lie_detector['SAR Backscatter (dB)'], color=color2, marker='D', linewidth=3, markersize=8, label='Infrastructure Load & Subsidence (SAR)')
ax2.set_ylabel('SAR Backscatter (dB)', color=color2, fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor=color2)

# ตกแต่งกราฟ
plt.title('The Lie Detector: Natural Soil Moisture vs Artificial Subsidence (Mesa, AZ)', fontsize=14, fontweight='bold')
fig.legend(loc='upper left', bbox_to_anchor=(0.15, 0.85))
ax1.grid(True, axis='y', linestyle='--', alpha=0.3)
plt.tight_layout()

# แสดงผล
plt.show()

print("\nตารางเปรียบเทียบ: ความชื้นในดิน (ธรรมชาติ) vs การยุบตัวของดิน (มนุษย์)")
display(df_lie_detector)

"""**ความชื้นของดินที่ลดลงสัมพันธ์กับสิ่งก่อสร้างที่เพิ่มขึ้น**"""

import ee
import pandas as pd
import matplotlib.pyplot as plt

# 1. โฟกัสไปที่พื้นที่วิกฤต Mesa, AZ (ทะเลทราย)
roi = ee.Geometry.Point([-111.602, 33.324]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]
data_list = []

print("กำลังประมวลผลโมเดล Causal Inference (SAR vs Soil Moisture)")

for year in years:
    start, end = f'{year}-06-01', f'{year}-08-31'

    # ดึงข้อมูล Sentinel-1 (SAR) เพื่อจับตาการขยายตัวของตึก
    s1 = ee.ImageCollection('COPERNICUS/S1_GRD') \
            .filterBounds(roi) \
            .filterDate(start, end) \
            .filter(ee.Filter.eq('instrumentMode', 'IW')) \
            .select('VV') \
            .median()

    sar_val = s1.reduceRegion(ee.Reducer.mean(), roi, 100).get('VV').getInfo()

    # ดึงข้อมูล ERA5 (Soil Moisture) วัดระดับความชื้นในหน้าดิน
    era = ee.ImageCollection("ECMWF/ERA5_LAND/MONTHLY_AGGR") \
            .filterBounds(roi) \
            .filterDate(start, end) \
            .median()
    sm_val = era.select('volumetric_soil_water_layer_1').reduceRegion(ee.Reducer.mean(), roi, 11000).get('volumetric_soil_water_layer_1').getInfo()

    data_list.append({
        'Year': year,
        'Infrastructure (SAR dB)': sar_val,
        'Soil Moisture (m3/m3)': sm_val
    })

df_causal = pd.DataFrame(data_list)
print("✅ ประมวลผลเสร็จสิ้น! กำลังวาดกราฟแบบแกนคู่ (Dual-Axis)...")


fig, ax1 = plt.subplots(figsize=(10, 5))

# เส้นที่ 1: การขยายตัวของตึก (แกนซ้าย)
color1 = '#e67e22'
ax1.set_xlabel('Year', fontsize=12)
ax1.set_ylabel('Infrastructure Growth (SAR VV dB)', color=color1, fontsize=12, fontweight='bold')
line1 = ax1.plot(df_causal['Year'], df_causal['Infrastructure (SAR dB)'], color=color1, linewidth=4, marker='s', markersize=8, label='Data Center Expansion (SAR)')
ax1.tick_params(axis='y', labelcolor=color1)

# เส้นที่ 2: ความชื้นในดินที่ลดลง (แกนขวา)
ax2 = ax1.twinx()
color2 = '#3498db'
ax2.set_ylabel('Soil Moisture Drop (m³/m³)', color=color2, fontsize=12, fontweight='bold')
line2 = ax2.plot(df_causal['Year'], df_causal['Soil Moisture (m3/m3)'], color=color2, linewidth=4, marker='o', markersize=8, linestyle='--', label='Soil Moisture Depletion (ERA5)')
ax2.tick_params(axis='y', labelcolor=color2)

lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc='upper center', bbox_to_anchor=(0.5, -0.15), ncol=2, fontsize=11)

plt.title('Causal Inference: Data Center Expansion vs Soil Moisture (Mesa, AZ)', fontsize=14, fontweight='bold')
plt.grid(True, linestyle=':', alpha=0.5)
plt.tight_layout()

# โชว์กราฟ
plt.show()

"""**Tri-Sensor Data Fusion**"""

import pandas as pd
import matplotlib.pyplot as plt

print("กำลังรวมรวมข้อมูล 3 มิติ (ความร้อน-น้ำ-แผ่นดิน) เพื่อหาความสัมพันธ์เชิงลึก")

# 1. สร้างตารางข้อมูล df_all
data = {
    'Year': [2020, 2021, 2022, 2023, 2024, 2025],
    'Daytime Temp (°C)': [53.49, 50.57, 50.48, 50.18, 49.77, 48.25],
    'Nighttime Temp (°C)': [29.03, 28.25, 28.56, 29.36, 30.88, 30.76],
    'Water Area (Hectares)': [11.14, 9.51, 18.05, 17.32, 31.07, 19.14],
    'SAR Backscatter (dB)': [-14.23, -13.73, -13.68, -13.26, -13.19, -13.12]
}
df_all = pd.DataFrame(data)

# 2. ปรับสเกลข้อมูล (Normalization 0-1)
df_norm = df_all.copy()
cols_to_norm = ['Nighttime Temp (°C)', 'Water Area (Hectares)', 'SAR Backscatter (dB)']

for col in cols_to_norm:
    min_val = df_all[col].min()
    max_val = df_all[col].max()
    df_norm[col] = (df_all[col] - min_val) / (max_val - min_val)

# 3. พล็อตกราฟ 3 เส้นทับซ้อนกัน
plt.figure(figsize=(11, 5))

plt.plot(df_norm['Year'], df_norm['SAR Backscatter (dB)'], marker='D', color='#8e44ad', linewidth=3, label='Infrastructure Load (SAR)')
plt.plot(df_norm['Year'], df_norm['Nighttime Temp (°C)'], marker='o', color='#e74c3c', linewidth=3, label='Trapped Heat (LST)')
plt.plot(df_norm['Year'], df_norm['Water Area (Hectares)'], marker='s', color='#1bc4d9', linewidth=3, label='Surface Water (NDWI)')

plt.title('Tri-Sensor Data Fusion: The Environmental Correlation (2020-2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Normalized Impact (0 to 1)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend(loc='upper left', bbox_to_anchor=(1.02, 1))
plt.tight_layout()

plt.show()
print("\nตารางข้อมูลดิบก่อนปรับสเกล:")
display(df_all)

"""**GeoAI Forecasting**

พยากรณ์ จำนวน data center  ปริมาณแหล่งน้ำ และ อุณหภูมิ
"""

from sklearn.linear_model import LinearRegression
import numpy as np

print("กำลังรัน AI พยากรณ์ผลกระทบล่วงหน้า 3 ปี (What-If Scenario)")

# 1. เทรนโมเดล ML (ให้ AI เรียนรู้ว่าถ้าตึก(SAR) เพิ่ม น้ำกับความร้อนจะเปลี่ยนไปยังไง)
X = df_all[['SAR Backscatter (dB)']].values
y_water = df_all['Water Area (Hectares)'].values
y_temp = df_all['Nighttime Temp (°C)'].values

model_water = LinearRegression().fit(X, y_water)
model_temp = LinearRegression().fit(X, y_temp)

# 2. จำลองอนาคต (สมมติให้ตึกขยายตัวหนาแน่นขึ้น 0.5 dB ทุกปี)
last_sar = df_all['SAR Backscatter (dB)'].iloc[-1]
future_sar = np.array([last_sar + 0.5, last_sar + 1.0, last_sar + 1.5]).reshape(-1, 1)
future_years = [2026, 2027, 2028]

pred_water = model_water.predict(future_sar)
pred_temp = model_temp.predict(future_sar)

df_future = pd.DataFrame({
    'Year': future_years,
    'SAR Backscatter (dB)': future_sar.flatten(),
    'Water Area (Hectares)': pred_water,
    'Nighttime Temp (°C)': pred_temp
})

# 3. เตรียมข้อมูลพล็อตกราฟ (รวบอดีต + อนาคต)
df_combined = pd.concat([df_all, df_future], ignore_index=True)
df_norm_comb = df_combined.copy()

for col in cols_to_norm:
    df_norm_comb[col] = (df_combined[col] - df_combined[col].min()) / (df_combined[col].max() - df_combined[col].min())

# ให้ปี 2025 เป็นจุดเชื่อมรอยต่อ
past = df_norm_comb[df_norm_comb['Year'] <= 2025]
future = df_norm_comb[df_norm_comb['Year'] >= 2025]

# 4. พล็อตกราฟ The Future Forecast
plt.figure(figsize=(12, 6))

# เส้นโครงสร้างตึก
plt.plot(past['Year'], past['SAR Backscatter (dB)'], marker='D', color='#8e44ad', linewidth=3, label='Past Infrastructure')
plt.plot(future['Year'], future['SAR Backscatter (dB)'], marker='D', linestyle='--', color='#8e44ad', linewidth=3, alpha=0.5, label='Predicted Infrastructure Growth')

# เส้นความร้อน
plt.plot(past['Year'], past['Nighttime Temp (°C)'], marker='o', color='#e74c3c', linewidth=3, label='Past Trapped Heat')
plt.plot(future['Year'], future['Nighttime Temp (°C)'], marker='o', linestyle='--', color='#e74c3c', linewidth=3, alpha=0.5, label='Predicted Heat Increase')

# เส้นน้ำ
plt.plot(past['Year'], past['Water Area (Hectares)'], marker='s', color='#1bc4d9', linewidth=3, label='Past Surface Water')
plt.plot(future['Year'], future['Water Area (Hectares)'], marker='s', linestyle='--', color='#1bc4d9', linewidth=3, alpha=0.5, label='Predicted Water Depletion')

plt.title('GeoAI Forecast: What-If Scenario for Data Center Expansion (2020-2028)', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Normalized Scale (0 to 1)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend(loc='center left', bbox_to_anchor=(1.02, 0.5))
plt.tight_layout()

plt.show()

print("\nตารางพยากรณ์ตัวเลขดิบ (2026-2028):")
display(df_future)

"""**กลุ่มที่ 2: พื้นที่เกษตรกรรมและที่ราบลุ่ม (ประเด็น: ทับซ้อนพื้นที่ทำกิน, การใช้น้ำบาดาล)**"""

import ee
import geemap

print("กำลังสร้างแผนที่ Time-Slider: ความชุ่มชื้นพืชไร่ (NDMI) 2020-2024")

# 1. กำหนดพิกัด Council Bluffs, IA
lat_ia, lon_ia = 41.221, -95.862
roi_ia = ee.Geometry.Point([lon_ia, lat_ia]).buffer(5000)

Map_Agri_Slider = geemap.Map(center=[lat_ia, lon_ia], zoom=13)
Map_Agri_Slider.add_basemap('SATELLITE')

# 2. กำหนดปีที่เราต้องการไล่ลำดับ
years_list = ee.List([2020, 2021, 2022, 2023, 2024])

# 3. สร้างฟังก์ชันดึงภาพ NDMI รายปีและตั้งค่าเวลา (Timestamp)
def create_ndmi_image(year):
    y = ee.Number(year)
    start_date = ee.Date.fromYMD(y, 6, 1)
    end_date = ee.Date.fromYMD(y, 8, 31)

    s2_img = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
               .filterBounds(roi_ia) \
               .filterDate(start_date, end_date) \
               .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20)) \
               .median() \
               .clip(roi_ia)

    # คำนวณดัชนีความชุ่มชื้น (NDMI)
    ndmi_img = s2_img.normalizedDifference(['B8', 'B11']).rename('NDMI')

    # ฝังเวลาเข้าไปในรูปภาพ เพื่อให้ Slider เรียงลำดับปีได้ถูกต้อง
    return ndmi_img.set('system:time_start', start_date.millis())

# 4. วนลูปสร้างเป็น คอลเล็กชั่นภาพ (Image Collection) 5 ปี
collection_ndmi = ee.ImageCollection(years_list.map(create_ndmi_image))

# 5. กำหนดพาเลทสี (แดง/น้ำตาล = แห้งแล้งดินยุบ, เหลือง = ปานกลาง, เขียว = ชุ่มชื้นสมบูรณ์)
ndmi_vis = {
    'min': -0.1,
    'max': 0.5,
    'palette': ['#d73027', '#fc8d59', '#fee08b', '#d9ef8b', '#91cf60', '#1a9850']
}

# 6. เพิ่มแถบ Time Slider ลงในแผนที่
Map_Agri_Slider.add_time_slider(collection_ndmi, ndmi_vis, time_interval=1.5)

# ตีเส้นขอบวงกลมสีขาว 5 กม.
outline = ee.Image().byte().paint(featureCollection=ee.FeatureCollection(roi_ia), color=1, width=2)
Map_Agri_Slider.addLayer(outline, {'palette': ['white']}, '5km Radius Border')

# แสดงผล
Map_Agri_Slider

"""**การกลืนกินพื้นที่ทำกิน (Land Displacement)**"""

import ee
import pandas as pd
import matplotlib.pyplot as plt

# พิกัด Council Bluffs, IA
lat_ia, lon_ia = 41.221, -95.862
roi_ia = ee.Geometry.Point([lon_ia, lat_ia]).buffer(5000)

# ข้อมูล CDL อัปเดตสมบูรณ์สุดถึงประมาณปี 2023
years_cdl = [2020, 2021, 2022, 2023]

crop_results = []
print("กำลังคำนวณพื้นที่เกษตรกรรม (Hectares) ที่สูญหายไปจากการขยายตัวของตึก")

for year in years_cdl:
    # ใช้ฐานข้อมูล USDA Cropland Data Layer
    cdl = ee.Image(f'USDA/NASS/CDL/{year}').select('cropland').clip(roi_ia)

    # รหัส 1-60 คือพื้นที่เพาะปลูกพืชเศรษฐกิจ
    is_crop = cdl.lte(60).And(cdl.gte(1))

    # คำนวณพื้นที่ (แปลงจากตารางเมตร เป็น เฮกตาร์)
    area_image = is_crop.multiply(ee.Image.pixelArea())
    crop_area_dict = area_image.reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=roi_ia,
        scale=30,
        maxPixels=1e9
    ).getInfo()

    crop_hectares = crop_area_dict.get('cropland') / 10000 if crop_area_dict.get('cropland') else 0

    crop_results.append({
        'Year': year,
        'Active Farmland (Hectares)': round(crop_hectares, 2)
    })

df_crop_loss = pd.DataFrame(crop_results)

# พล็อตกราฟพื้นที่เกษตรที่หายไป
plt.figure(figsize=(9, 5))
color_loss = '#d35400'

plt.plot(df_crop_loss['Year'], df_crop_loss['Active Farmland (Hectares)'], marker='s', color=color_loss, linewidth=4, markersize=10, label='Active Farmland Area')
plt.fill_between(df_crop_loss['Year'], df_crop_loss['Active Farmland (Hectares)'], color=color_loss, alpha=0.1)

# ตกแต่งกราฟ
plt.title('Agricultural Land Displacement (Council Bluffs, IA)', fontsize=14, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Farmland Area (Hectares)', color=color_loss, fontsize=12)
plt.grid(True, linestyle='--', alpha=0.3)
plt.legend(loc='upper right')
plt.tight_layout()

# แสดงผล
plt.show()

print("\nตารางพื้นที่เพาะปลูก (หากค่าน้อยลง แปลว่าพื้นที่ทำกินหายไป):")
display(df_crop_loss)

"""**กลุ่มที่ 3: เขตป่าไม้และใกล้แหล่งน้ำอุดมสมบูรณ์ (ประเด็น: นิเวศวิทยารอบแม่น้ำ, การปล่อยน้ำร้อนลงแหล่งน้ำ)**"""

import ee
import geemap

print("กำลังสร้างแผนที่ Time-Slider: มลภาวะความร้อนบนผิวน้ำ ปี 2020-2024")

lat_or, lon_or = 45.604, -121.144
roi_or = ee.Geometry.Point([lon_or, lat_or]).buffer(3000)

Map_Slider = geemap.Map(center=[lat_or, lon_or], zoom=14)
Map_Slider.add_basemap('SATELLITE')

# กำหนดปีที่เราต้องการไล่ลำดับ
years_list = ee.List([2020, 2021, 2022, 2023, 2024])

# สร้างฟังก์ชันดึงภาพรายปีและแนบ "เวลา (Timestamp)" เข้าไปให้ Slider รู้จัก
def create_yearly_image(year):
    y = ee.Number(year)
    start_date = ee.Date.fromYMD(y, 6, 1)
    end_date = ee.Date.fromYMD(y, 8, 31)

    img = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2") \
            .filterBounds(roi_or) \
            .filterDate(start_date, end_date) \
            .filter(ee.Filter.lt('CLOUD_COVER', 20)) \
            .median() \
            .clip(roi_or)

    # แปลงเป็นเซลเซียส
    temp_c = img.select('ST_B10').multiply(0.00341802).add(149.0).subtract(273.15)

    # สร้างหน้ากากน้ำ
    ndwi = img.normalizedDifference(['SR_B3', 'SR_B5'])
    water_mask = ndwi.gt(0)

    # ตัดความร้อนบนบกทิ้ง และตั้งค่าเวลาเพื่อให้ Slider เรียงลำดับถูก
    masked_temp = temp_c.updateMask(water_mask)
    return masked_temp.set('system:time_start', start_date.millis())

# นำฟังก์ชันไปวนลูปสร้างเป็น คอลเล็กชั่นภาพ (Image Collection) 5 ปี
collection = ee.ImageCollection(years_list.map(create_yearly_image))

# กำหนดสีความร้อน (น้ำเงิน=เย็น, แดง=ร้อน)
river_vis = {'min': 15, 'max': 24, 'palette': ['#0000ff', '#00ffff', '#ffff00', '#ff0000']}

# เพิ่มแถบ Time Slider ลงในแผนที่ (สามารถกด Play ให้สามารถเล่นอัตโนมัติได้)
Map_Slider.add_time_slider(collection, river_vis, time_interval=1.5)

# วาดกรอบวงกลมรัศมี 3 กม.
outline = ee.Image().byte().paint(featureCollection=ee.FeatureCollection(roi_or), color=1, width=2)
Map_Slider.addLayer(outline, {'palette': ['white']}, '3km Radius Border')

# แสดงผล
Map_Slider

"""**มลภาวะทางความร้อน (Thermal Pollution)' กลับลงแม่น้ำ ผลกระทบต่อนิเวศทางน้ำ**"""

import ee
import pandas as pd
import matplotlib.pyplot as plt

# 1. พิกัด The Dalles, Oregon (Data Center ริมแม่น้ำ Columbia)
lat_or, lon_or = 45.604, -121.144
roi_or = ee.Geometry.Point([lon_or, lat_or]).buffer(3000) # รัศมี 3 กม. เพื่อโฟกัสตรงจุดปล่อยน้ำทิ้ง
years = [2020, 2021, 2022, 2023, 2024, 2025]

river_results = []
print(" กำลังรัน AI แยกแยะผิวน้ำ เพื่อวิเคราะห์ 'มลภาวะทางความร้อนในแม่น้ำ' และ 'ป่าไม้ริมน้ำ'")

for year in years:
    start = f'{year}-06-01'
    end = f'{year}-08-31'

    # ส่วนที่ 1: ดึงความสมบูรณ์ของป่าไม้ (NDVI) ด้วย Sentinel-2
    s2 = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
           .filterBounds(roi_or) \
           .filterDate(start, end) \
           .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20)) \
           .median()

    ndvi = s2.normalizedDifference(['B8', 'B4']).rename('NDVI')
    mean_ndvi_dict = ndvi.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi_or, scale=30, maxPixels=1e9).getInfo()
    ndvi_val = mean_ndvi_dict.get('NDVI') if mean_ndvi_dict else None


    # ส่วนที่ 2: ดึงอุณหภูมิผิวน้ำ (River Surface Temp) ด้วย Landsat 8
    l8 = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2") \
           .filterBounds(roi_or) \
           .filterDate(start, end) \
           .filter(ee.Filter.lt('CLOUD_COVER', 20)) \
           .median()

    temp_c = l8.select('ST_B10').multiply(0.00341802).add(149.0).subtract(273.15).rename('LST')

    # เทคนิคขั้นสูง: สร้าง Water Mask (กรองให้เหลือแค่น้ำ) โดยใช้ NDWI (B3 - B5)
    water_index = l8.normalizedDifference(['SR_B3', 'SR_B5'])
    is_water = water_index.gt(0) # ตรงไหนค่า > 0 แปลว่าเป็นน้ำ

    # สั่งให้ AI วัดอุณหภูมิเฉพาะจุดที่เป็น 'ผิวน้ำ' เท่านั้น (ละความร้อนบนบก)
    river_temp = temp_c.updateMask(is_water)

    mean_river_temp_dict = river_temp.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi_or, scale=30, maxPixels=1e9).getInfo()
    temp_val = mean_river_temp_dict.get('LST') if mean_river_temp_dict else None

    # เก็บข้อมูล
    river_results.append({
        'Year': year,
        'Forest Health (NDVI)': round(ndvi_val, 3) if ndvi_val else 0,
        'River Surface Temp (°C)': round(temp_val, 2) if temp_val else 0
    })

df_river = pd.DataFrame(river_results)

# 2. พล็อตกราฟแกนคู่ (Dual-Axis: ป่าไม้ริมน้ำ vs อุณหภูมิผิวน้ำ)
fig, ax1 = plt.subplots(figsize=(10, 6))

# แกนซ้าย: ความหนาแน่นของป่าไม้ริมน้ำ
color1 = '#27ae60'
ax1.bar(df_river['Year'], df_river['Forest Health (NDVI)'], color=color1, alpha=0.4, label='Forest Health (NDVI)')
ax1.set_xlabel('Year', fontsize=12)
ax1.set_ylabel('Vegetation Index (NDVI)', color=color1, fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor=color1)

# แกนขวา: อุณหภูมิผิวน้ำในแม่น้ำ
ax2 = ax1.twinx()
color2 = '#c0392b'
ax2.plot(df_river['Year'], df_river['River Surface Temp (°C)'], color=color2, marker='o', linewidth=4, markersize=10, label='River Surface Temp (°C)')
ax2.set_ylabel('River Water Temperature (°C)', color=color2, fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor=color2)

# ตกแต่งกราฟ
plt.title('GeoAI Module 3: Thermal Pollution & River Ecology (The Dalles, OR)', fontsize=14, fontweight='bold')
fig.legend(loc='upper left', bbox_to_anchor=(0.15, 0.85))
ax1.grid(True, axis='y', linestyle='--', alpha=0.3)
plt.tight_layout()

# แสดงผล
plt.show()

print("\nตารางอุณหภูมิผิวน้ำ (ยิ่งน้ำร้อน ยิ่งส่งผลเสียต่อระบบนิเวศ):")
display(df_river)

"""**กลุ่มที่ 4: เขตร้อนชื้นและเมืองหนาแน่น (ประเด็น: การใช้ไฟสูง, ความร้อนสะสมในเขตเมือง - Urban Heat Island)**"""

import ee
import geemap

print("กำลังสร้างแผนที่ Time-Slider: การดูดพลังงานไฟฟ้า (Nighttime Lights) 2020-2024")

# 1. พิกัด Ashburn, VA (ศูนย์กลาง Data Center ของโลก)
lat_va, lon_va = 39.043, -77.487
roi_va = ee.Geometry.Point([lon_va, lat_va]).buffer(5000)

Map_Urban_Slider = geemap.Map(center=[lat_va, lon_va], zoom=13)
Map_Urban_Slider.add_basemap('CartoDB.DarkMatter')

years_list = ee.List([2020, 2021, 2022, 2023, 2024])

# 2. สร้างฟังก์ชันดึงภาพดาวเทียมแสงไฟกลางคืน (VIIRS) รายปี
def create_viirs_image(year):
    y = ee.Number(year)
    start_date = ee.Date.fromYMD(y, 1, 1)
    end_date = ee.Date.fromYMD(y, 12, 31)

    # ดาวเทียม VIIRS วัดรังสีแสงสว่างบนพื้นโลก
    viirs_img = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG") \
                  .filterBounds(roi_va) \
                  .filterDate(start_date, end_date) \
                  .median() \
                  .clip(roi_va)

    # เลือกแบนด์ 'avg_rad' (Average Radiance)
    lights = viirs_img.select('avg_rad')

    return lights.set('system:time_start', start_date.millis())

# 3. วนลูปสร้างเป็น คอลเล็กชั่นภาพ 5 ปี
collection_viirs = ee.ImageCollection(years_list.map(create_viirs_image))

# 4. กำหนดพาเลทสี (ดำ -> ม่วง -> แดง -> เหลือง -> ขาวสว่างจ้า)
# แสงไฟยิ่งสว่าง = มีการใช้ไฟฟ้า/พลังงาน มหาศาล
viirs_vis = {
    'min': 0,
    'max': 60,
    'palette': ['#000000', '#4a235a', '#c0392b', '#f1c40f', '#ffffff']
}

# 5. เพิ่มแถบ Time Slider ลงในแผนที่
Map_Urban_Slider.add_time_slider(collection_viirs, viirs_vis, time_interval=1.5)

# ตีเส้นขอบวงกลมสีขาว 5 กม.
outline = ee.Image().byte().paint(featureCollection=ee.FeatureCollection(roi_va), color=1, width=2)
Map_Urban_Slider.addLayer(outline, {'palette': ['white']}, '5km Radius Border')

# แสดงผล
Map_Urban_Slider

import ee
import pandas as pd
import matplotlib.pyplot as plt

print(" กำลังวิเคราะห์ 'การสูบพลังงานไฟฟ้า' เทียบกับ 'โดมความร้อนเมือง'")

# พิกัด Ashburn, VA
lat_va, lon_va = 39.043, -77.487
roi_va = ee.Geometry.Point([lon_va, lat_va]).buffer(5000)
years = [2020, 2021, 2022, 2023, 2024, 2025]

urban_results = []

for year in years:
    # 1. ดึงข้อมูลการใช้ไฟฟ้า (ดาวเทียม VIIRS Nighttime Lights)
    viirs = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG") \
              .filterBounds(roi_va) \
              .filterDate(f'{year}-01-01', f'{year}-12-31') \
              .median()

    light_val = viirs.select('avg_rad').reduceRegion(reducer=ee.Reducer.mean(), geometry=roi_va, scale=500, maxPixels=1e9).getInfo()
    light = light_val.get('avg_rad') if light_val else None

    # 2. ดึงข้อมูลความร้อนสะสมในเมือง (Landsat 8 LST)
    l8 = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2") \
           .filterBounds(roi_va) \
           .filterDate(f'{year}-05-01', f'{year}-10-31') \
           .filter(ee.Filter.lt('CLOUD_COVER', 60)) \
           .median()

    temp_c = l8.select('ST_B10').multiply(0.00341802).add(149.0).subtract(273.15)
    temp_val = temp_c.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi_va, scale=30, maxPixels=1e9).getInfo()
    temp = temp_val.get('ST_B10') if temp_val else None

    urban_results.append({
        'Year': year,
        'Energy Consumption Proxy (VIIRS)': round(light, 2) if light else 0,
        'Urban Heat Island Temp (°C)': round(temp, 2) if temp else 0
    })

df_urban = pd.DataFrame(urban_results)

# 3. พล็อตกราฟแกนคู่ (Dual-Axis)
fig, ax1 = plt.subplots(figsize=(10, 6))

# แกนซ้าย: พลังงานไฟฟ้า
color1 = '#f39c12'
ax1.bar(df_urban['Year'], df_urban['Energy Consumption Proxy (VIIRS)'], color=color1, alpha=0.5, label='Energy Drain (VIIRS)')
ax1.set_xlabel('Year', fontsize=12)
ax1.set_ylabel('Electricity Proxy (Light Radiance)', color=color1, fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor=color1)

# แกนขวา: ความร้อนสะสมในเมือง
ax2 = ax1.twinx()
color2 = '#c0392b'
ax2.plot(df_urban['Year'], df_urban['Urban Heat Island Temp (°C)'], color=color2, marker='D', linewidth=4, markersize=9, label='Urban Heat Island Temp (°C)')
ax2.set_ylabel('Surface Temperature (°C)', color=color2, fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor=color2)

# ตกแต่งกราฟ
plt.title('GeoAI Module 4: Energy Drain vs Urban Heat Island (Ashburn, VA)', fontsize=14, fontweight='bold')
fig.legend(loc='upper left', bbox_to_anchor=(0.15, 0.85))
ax1.grid(True, axis='y', linestyle='--', alpha=0.3)
plt.tight_layout()

# แสดงผล
plt.show()

print("\n ตารางความสัมพันธ์ (ไฟฟ้ายิ่งใช้มาก เมืองยิ่งร้อนจัด):")
display(df_urban)

"""**EXPORT: GeoSentinel Monthly Time-Series Dashboard**"""

import ee
import pandas as pd
import numpy as np

print("กำลังสแกนข้อมูลดาวเทียมแบบ 'รายเดือน' ตั้งแต่ 2020-2025")
print("ระบบกัน Error กรณีเมฆบัง 100%  กรุณารอสักครู่")

# 1. ชุดพิกัด 10 Data Centers
dc_locations = {
    'Meta_Mesa_AZ': {'lat': 33.324, 'lon': -111.602},
    'Apple_Reno_NV': {'lat': 39.556, 'lon': -119.467},
    'Meta_EagleMountain_UT': {'lat': 40.260, 'lon': -112.046},
    'Google_CouncilBluffs_IA': {'lat': 41.221, 'lon': -95.862},
    'Meta_NewAlbany_OH': {'lat': 40.091, 'lon': -82.766},
    'Google_TheDalles_OR': {'lat': 45.604, 'lon': -121.144},
    'Meta_Prineville_OR': {'lat': 44.301, 'lon': -120.814},
    'Google_Lenoir_NC': {'lat': 35.897, 'lon': -81.547},
    'AWS_Ashburn_VA': {'lat': 39.018, 'lon': -77.472},
    'Microsoft_SanAntonio_TX': {'lat': 29.435, 'lon': -98.694}
}

months = pd.date_range(start='2020-01-01', end='2025-12-01', freq='MS')
dashboard_data = []

# ฟังก์ชันคำนวณบน GEE Server (ลดโอกาส Error จากภาพว่างเปล่า)
def calc_lst(img):
    return img.select('ST_B10').multiply(0.00341802).add(149.0).subtract(273.15).rename('LST_C')

def calc_s2(img):
    ndwi = img.normalizedDifference(['B3', 'B8']).rename('NDWI')
    ndvi = img.normalizedDifference(['B8', 'B4']).rename('NDVI')
    ndbi = img.normalizedDifference(['B11', 'B8']).rename('NDBI')
    return img.addBands([ndwi, ndvi, ndbi])

# 2. วนลูปดึงข้อมูล
for name, coords in dc_locations.items():
    print(f" กำลังสแกนพื้นที่: {name}")
    roi = ee.Geometry.Point([coords['lon'], coords['lat']]).buffer(5000)

    for dt in months:
        year_month = dt.strftime('%Y-%m')

        # ขยายกรอบเวลาค้นหาภาพเป็น 3 เดือน ป้องกันเมฆบังหมด
        start_str = (dt - pd.DateOffset(months=1)).strftime('%Y-%m-%d')
        end_str = (dt + pd.DateOffset(months=1)).strftime('%Y-%m-%d')
        exact_month_start = dt.strftime('%Y-%m-%d')
        exact_month_end = (dt + pd.DateOffset(months=1)).strftime('%Y-%m-%d')

        try:
            # LST
            l8 = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2").filterBounds(roi).filterDate(start_str, end_str).map(calc_lst).median()
            lst_val = l8.reduceRegion(ee.Reducer.mean(), roi, 100).get('LST_C').getInfo()

            # NDWI, NDVI, NDBI
            s2 = ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterBounds(roi).filterDate(start_str, end_str).map(calc_s2).median()
            s2_res = s2.reduceRegion(ee.Reducer.mean(), roi, 100).getInfo() or {}

            # Precipitation & Soil Moisture
            era5 = ee.ImageCollection("ECMWF/ERA5_LAND/MONTHLY_AGGR").filterBounds(roi).filterDate(exact_month_start, exact_month_end).median()
            era5_res = era5.reduceRegion(ee.Reducer.mean(), roi, 11000).getInfo() or {}

            precip_val = era5_res.get('total_precipitation')
            if precip_val is not None: precip_val *= 1000

            # บันทึกข้อมูลที่ดึงมาใช้งานได้
            dashboard_data.append({
                'data_center_name': name, 'latitude': coords['lat'], 'longitude': coords['lon'], 'year_month': year_month,
                'mean_LST_C': lst_val, 'mean_NDWI': s2_res.get('NDWI'), 'mean_NDVI': s2_res.get('NDVI'),
                'mean_NDBI': s2_res.get('NDBI'), 'precipitation_mm': precip_val, 'soil_moisture': era5_res.get('volumetric_soil_water_layer_1')
            })
        except Exception as e:
            # ถ้าระบบ GEE ล่มในเดือนนั้น ให้บันทึก NaN (ค่าว่าง) แทน เพื่อรักษาโครงสร้างตารางเอาไว้
            dashboard_data.append({
                'data_center_name': name, 'latitude': coords['lat'], 'longitude': coords['lon'], 'year_month': year_month,
                'mean_LST_C': np.nan, 'mean_NDWI': np.nan, 'mean_NDVI': np.nan, 'mean_NDBI': np.nan,
                'precipitation_mm': np.nan, 'soil_moisture': np.nan
            })

df = pd.DataFrame(dashboard_data)


print(" ดาวน์โหลดเสร็จสิ้น กำลังแก้ไขข้อมูลแหว่งและคำนวณดัชนี")

# เรียงลำดับข้อมูล
df.sort_values(by=['data_center_name', 'year_month'], inplace=True)

# เติมข้อมูลที่ขาดหาย (Interpolate)
cols_to_fill = ['mean_LST_C', 'mean_NDWI', 'mean_NDVI', 'mean_NDBI', 'precipitation_mm', 'soil_moisture']
df[cols_to_fill] = df.groupby('data_center_name')[cols_to_fill].transform(lambda x: x.interpolate(method='linear', limit_direction='both'))

# คำนวณความเปลี่ยนแปลง 1 ปี (1Y Change)
df['lst_change_1y'] = df.groupby('data_center_name')['mean_LST_C'].diff(periods=12).fillna(0)
df['ndwi_change_1y'] = df.groupby('data_center_name')['mean_NDWI'].diff(periods=12).fillna(0)
df['ndvi_change_1y'] = df.groupby('data_center_name')['mean_NDVI'].diff(periods=12).fillna(0)
df['ndbi_change_1y'] = df.groupby('data_center_name')['mean_NDBI'].diff(periods=12).fillna(0)

# ฟังก์ชัน Normalize
def norm_bad_if_high(s):
    diff = s.max() - s.min()
    return ((s - s.min()) / diff * 100) if diff != 0 else pd.Series(50, index=s.index)

def norm_bad_if_low(s):
    diff = s.max() - s.min()
    return ((s.max() - s) / diff * 100) if diff != 0 else pd.Series(50, index=s.index)

#  ECI Score
df['ECI_score'] = (
    norm_bad_if_high(df['lst_change_1y']) * 0.3 +
    norm_bad_if_high(df['ndbi_change_1y']) * 0.3 +
    norm_bad_if_low(df['ndwi_change_1y']) * 0.2 +
    norm_bad_if_low(df['ndvi_change_1y']) * 0.2
).round(2)

#  ESS Score
df['ESS_score'] = (
    norm_bad_if_high(df['mean_LST_C']) * 0.3 +
    norm_bad_if_high(df['mean_NDBI']) * 0.3 +
    norm_bad_if_low(df['mean_NDWI']) * 0.2 +
    norm_bad_if_low(df['soil_moisture']) * 0.2
).round(2)

#  Risk Score
df['risk_score'] = ((df['ECI_score'] + df['ESS_score']) / 2).round(2)

def get_risk_level(score):
    if score >= 75: return 'Critical'
    elif score >= 50: return 'Concern'
    elif score >= 25: return 'Watch'
    else: return 'Stable'

df['risk_level'] = df['risk_score'].apply(get_risk_level)

# พยากรณ์ความเสี่ยงล่วงหน้า (AI Trend Forecasting)
df['risk_trend_monthly'] = df.groupby('data_center_name')['risk_score'].diff(periods=12).fillna(0) / 12
df['forecast_risk_score_6m'] = (df['risk_score'] + (df['risk_trend_monthly'] * 6)).clip(0, 100).round(2)
df['forecast_risk_level_6m'] = df['forecast_risk_score_6m'].apply(get_risk_level)
df['forecast_risk_score_12m'] = (df['risk_score'] + (df['risk_trend_monthly'] * 12)).clip(0, 100).round(2)
df['forecast_risk_level_12m'] = df['forecast_risk_score_12m'].apply(get_risk_level)


final_columns = [
    'data_center_name', 'latitude', 'longitude', 'year_month',
    'mean_LST_C', 'mean_NDWI', 'mean_NDVI', 'mean_NDBI',
    'precipitation_mm', 'soil_moisture',
    'lst_change_1y', 'ndwi_change_1y', 'ndvi_change_1y', 'ndbi_change_1y',
    'ECI_score', 'ESS_score',
    'risk_score', 'risk_level',
    'forecast_risk_score_6m', 'forecast_risk_level_6m',
    'forecast_risk_score_12m', 'forecast_risk_level_12m'
]

df_final = df[final_columns].copy()

#เติมค่าว่างทั้งหมด (ถ้ายังมีหลงเหลือ) ให้เป็น 0
df_final.fillna(0, inplace=True)

display(df_final.head())

# Export CSV
df_final.to_csv("geosentinel_monthly_dashboard_data.csv", index=False)
print("\nบันทึกไฟล์ 'geosentinel_monthly_dashboard_data.csv' สำเร็จ")
print(" ระบบทำงานสมบูรณ์ ข้อมูลครบทุกคอลัมน์ สำหรับสร้าง Dashboard ")